# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ef955b0fa34be9e1fba5b2fdd289ff0087b32929a31dc6d792802b3422946b51001efbaac480baae591b7a1e52848899a6311a72d94152dc7d850bf78fca341

test:
  secret_key_base: fa50377f80a58fd4ed05b8aa70e4efbfb21876313929da42d577bafdd9191a9600a9a33afa8d708d4d1b2cec8db99f0f894f75bfd0917cf4f35f1ca54f24cb73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
